[
  {
    "id": 1,
    "date": "2026-02-19",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 48.83,
    "qty": 8,
    "avg_price": 48.83,
    "exec_id": "RESTORE_TQQQ_1",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 2,
    "date": "2026-02-20",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 50.06,
    "qty": 12,
    "avg_price": 50.06,
    "exec_id": "RESTORE_TQQQ_2",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 3,
    "date": "2026-02-23",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 48.24,
    "qty": 26,
    "avg_price": 48.24,
    "exec_id": "RESTORE_TQQQ_3",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 4,
    "date": "2026-02-24",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 49.78,
    "qty": 12,
    "avg_price": 49.78,
    "exec_id": "RESTORE_TQQQ_4",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 5,
    "date": "2026-02-25",
    "ticker": "TQQQ",
    "side": "SELL",
    "price": 51.87,
    "qty": 34,
    "avg_price": 51.87,
    "exec_id": "RESTORE_TQQQ_5",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 6,
    "date": "2026-02-26",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 50.05,
    "qty": 6,
    "avg_price": 50.05,
    "exec_id": "RESTORE_TQQQ_6",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 7,
    "date": "2026-02-27",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 49.52,
    "qty": 6,
    "avg_price": 49.52,
    "exec_id": "RESTORE_TQQQ_7",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 8,
    "date": "2026-03-02",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 49.70,
    "qty": 6,
    "avg_price": 49.70,
    "exec_id": "RESTORE_TQQQ_8",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 9,
    "date": "2026-03-03",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 47.23,
    "qty": 26,
    "avg_price": 47.23,
    "exec_id": "RESTORE_TQQQ_9",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 10,
    "date": "2026-03-05",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 49.80,
    "qty": 6,
    "avg_price": 49.80,
    "exec_id": "RESTORE_TQQQ_10",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 11,
    "date": "2026-03-10",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 49.40,
    "qty": 6,
    "avg_price": 49.40,
    "exec_id": "RESTORE_TQQQ_11",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 12,
    "date": "2026-03-11",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 49.35,
    "qty": 6,
    "avg_price": 49.35,
    "exec_id": "RESTORE_TQQQ_12",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 13,
    "date": "2026-03-12",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 46.83,
    "qty": 13,
    "avg_price": 46.83,
    "exec_id": "RESTORE_TQQQ_13",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 14,
    "date": "2026-03-13",
    "ticker": "TQQQ",
    "side": "SELL",
    "price": 45.93,
    "qty": 51,
    "avg_price": 45.93,
    "exec_id": "RESTORE_TQQQ_14",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 15,
    "date": "2026-03-16",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 47.46,
    "qty": 13,
    "avg_price": 47.46,
    "exec_id": "RESTORE_TQQQ_15",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 16,
    "date": "2026-03-18",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 46.10,
    "qty": 14,
    "avg_price": 46.10,
    "exec_id": "RESTORE_TQQQ_16",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 17,
    "date": "2026-03-19",
    "ticker": "TQQQ",
    "side": "BUY",
    "price": 45.69,
    "qty": 130,
    "avg_price": 48.13,
    "exec_id": "RESTORE_TQQQ_17",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 18,
    "date": "2026-03-02",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 62.76,
    "qty": 189,
    "avg_price": 62.76,
    "exec_id": "RESTORE_SOXL_1",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 19,
    "date": "2026-03-03",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 55.43,
    "qty": 66,
    "avg_price": 55.43,
    "exec_id": "RESTORE_SOXL_2",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 20,
    "date": "2026-03-03",
    "ticker": "SOXL",
    "side": "SELL",
    "price": 56.54,
    "qty": 21,
    "avg_price": 56.54,
    "exec_id": "RESTORE_SOXL_3",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 21,
    "date": "2026-03-10",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 54.59,
    "qty": 23,
    "avg_price": 54.59,
    "exec_id": "RESTORE_SOXL_4",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 22,
    "date": "2026-03-11",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 56.09,
    "qty": 23,
    "avg_price": 56.09,
    "exec_id": "RESTORE_SOXL_5",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 23,
    "date": "2026-03-12",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 50.28,
    "qty": 25,
    "avg_price": 50.28,
    "exec_id": "RESTORE_SOXL_6",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 24,
    "date": "2026-03-13",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 50.72,
    "qty": 25,
    "avg_price": 50.72,
    "exec_id": "RESTORE_SOXL_7",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 25,
    "date": "2026-03-16",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 53.69,
    "qty": 20,
    "avg_price": 53.69,
    "exec_id": "RESTORE_SOXL_8",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 26,
    "date": "2026-03-17",
    "ticker": "SOXL",
    "side": "SELL",
    "price": 54.95,
    "qty": 35,
    "avg_price": 54.95,
    "exec_id": "RESTORE_SOXL_9",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 27,
    "date": "2026-03-18",
    "ticker": "SOXL",
    "side": "SELL",
    "price": 54.02,
    "qty": 79,
    "avg_price": 54.02,
    "exec_id": "RESTORE_SOXL_10",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 28,
    "date": "2026-03-19",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 54.85,
    "qty": 22,
    "avg_price": 54.85,
    "exec_id": "RESTORE_SOXL_11",
    "is_reverse": false,
    "desc": "수동복원"
  },
  {
    "id": 29,
    "date": "2026-03-20",
    "ticker": "SOXL",
    "side": "BUY",
    "price": 50.17,
    "qty": 25,
    "avg_price": 55.67,
    "exec_id": "RESTORE_SOXL_12",
    "is_reverse": false,
    "desc": "수동복원"
  }
]
